var b1 =  new Ball("red",3,390,790);
var b2 =  new Ball("red-",11);
var b3 =  new Ball("green",6);
var b4 =  new Ball("green-",14);
var b5 =  new Ball("yellow",1);
var b6 =  new Ball("yellow-",9);
var b7 =  new Ball("pink",5);
var b8 =  new Ball("pink-",13);
var b9 =  new Ball("black",8);
var b10 = new Ball("blue",2);
var b11 = new Ball("blue-",10);
var b12 = new Ball("purple",4);
var b13 = new Ball("purple-",12);
var b14 = new Ball("darkred",7);
var b15 = new Ball("darkred-",15);
var b16 = new Ball("white",0);

b1.render();
b2.render();
b3.render();
b4.render();
b5.render();
b6.render();
b7.render();
b8.render();
b9.render();
b10.render();
b11.render();
b12.render();
b13.render();
b14.render();
b15.render();
b16.render();
